language: go

go:
  - 1.4
  - 1.4.3
  - 1.5.1
  - tip

addons:
  apt:
    packages:
    - libpcap0.8-dev

install:
  - go get -v golang.org/x/tools/cmd/vet
  - go get -d -v ./...

script:
  - go tool vet -all -v . || true
  - go generate
  - go build -v ./...
